# Generated by Django 5.2 on 2025-04-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_user_readinglist_owner_book_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
