# Generated by Django 5.2 on 2025-04-13 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_readinglist_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='body',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='title',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
