# Generated by Django 5.2 on 2025-04-13 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_review_options_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='scheduled_for',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='topic',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='organizer',
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.book'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
