# Generated by Django 5.2 on 2025-04-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_scheduled_for_meeting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.book'),
        ),
    ]
